[package]
name = "zoid-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zoid-model = { path = "../zoid-model" }
serde = { workspace = true }
serde_ignored = { workspace = true }
serde_json = { workspace = true }
ulid = { workspace = true }
rusqlite = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
chacha20poly1305 = { workspace = true }
rand = { workspace = true }
percent-encoding = "2"
reqwest = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
tempfile = { workspace = true }
