[package]
name = "zoid-core"
version = "0.0.0"
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
ulid = { workspace = true }
rusqlite = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
chacha20poly1305 = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
tempfile = { workspace = true }
