[package]
name = "zoid-tools"
version.workspace = true
edition.workspace = true

[dependencies]
shlex = "2.0"
zoid-provider = { path = "../zoid-provider" }
zoid-web = { path = "../zoid-web" }
serde_json = { workspace = true }
regex = { workspace = true }
globset = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29", default-features = false, features = ["signal"] }
